global:
  resolve_timeout: 5m

route:
  receiver: "discord"
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m

receivers:
  - name: "discord"
    discord_configs:
      - webhook_url: ""
        title: "{{ .CommonAnnotations.summary }}"
        message: |
          {{ range .Alerts -}}
          **Status:** {{ .Status }}
          **Severity:** {{ .Labels.severity }}
          **Description:** {{ .Annotations.description }}
          {{ end }}
