services:
  minecraft:
    build:
      context: ./minecraft
    container_name: minecraft
    environment:
      EULA: "true"
      TZ: "Asia/Tokyo"
      JAVA_OPTS: "-Xms2G -Xmx8G -XX:+UseG1GC"
    ports:
      - "25519:25519"
    volumes:
      - ./data:/srv/minecraft
    restart: unless-stopped

  mc_monitor:
    image: itzg/mc-monitor:latest
    container_name: mc_monitor
    command:
      - export-for-prometheus
    environment:
      TZ: "Asia/Tokyo"
      EXPORT_PORT: "8080"
      EXPORT_SERVERS: "minecraft:25519"
    expose:
      - "8080"
    depends_on:
      - minecraft
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    volumes:
      - prom-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./rules:/etc/prometheus/rules:ro
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD}"
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Asia/Tokyo"
    env_file:
      - .env
    volumes:
      - ./ddclient:/config
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    restart: unless-stopped

volumes:
  # mc-data:
  prom-data:
  grafana-data:

